[FIX] : Fix dataclass field param to default_factory
ValueError: mutable default <class 'dict'> for field request_headers is not allowed: use default_factory

Should be default_factory= instead of default=